"""add_company_model

Revision ID: b5e55d2eabc8
Revises: 001
Create Date: 2025-11-25 20:10:22.904109

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql
import core.models

# revision identifiers, used by Alembic.
revision = 'b5e55d2eabc8'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('companies',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('address', sa.Text(), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lng', sa.Float(), nullable=True),
    sa.Column('owner_id', core.models.GUID(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('breakdown_requests', sa.Column('company_id', sa.Integer(), nullable=True))
    op.alter_column('breakdown_requests', 'status',
               existing_type=mysql.ENUM('REQUESTED', 'PENDING_TECHNICIAN', 'ACCEPTED', 'ON_THE_WAY', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_TECHNICIAN_FOUND'),
               type_=sa.String(length=30),
               existing_nullable=False)
    op.alter_column('breakdown_requests', 'payment_status',
               existing_type=mysql.ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED'),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.create_foreign_key(None, 'breakdown_requests', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('company_id', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('technician_type', sa.String(length=20), nullable=True))
    op.create_foreign_key(None, 'users', 'companies', ['company_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='foreignkey')
    op.drop_column('users', 'technician_type')
    op.drop_column('users', 'company_id')
    op.drop_constraint(None, 'breakdown_requests', type_='foreignkey')
    op.alter_column('breakdown_requests', 'payment_status',
               existing_type=sa.String(length=20),
               type_=mysql.ENUM('PENDING', 'PAID', 'FAILED', 'REFUNDED'),
               existing_nullable=False)
    op.alter_column('breakdown_requests', 'status',
               existing_type=sa.String(length=30),
               type_=mysql.ENUM('REQUESTED', 'PENDING_TECHNICIAN', 'ACCEPTED', 'ON_THE_WAY', 'ARRIVED', 'IN_PROGRESS', 'COMPLETED', 'CANCELLED', 'NO_TECHNICIAN_FOUND'),
               existing_nullable=False)
    op.drop_column('breakdown_requests', 'company_id')
    op.drop_table('companies')
    # ### end Alembic commands ###
